import assert from 'node:assert/strict';
import worker from '../src/index.mjs';
import {MODERATION_MODELS, moderationInput} from '../../coloring-sheets-api/src/moderation.mjs';
let calls=0;
const env={LAB_ACCESS_KEY:'test-key',AI_GATEWAY_ID:'coloring-sheets',LIMITER:{limit:async()=>({success:true})},AI:{run:async(model,input)=>{
  calls++;assert.equal(input.state.description,'A friendly flower');
  if(model===MODERATION_MODELS.clef)throw Error('private upstream details');
  const answers=Object.fromEntries(Object.keys(moderationInput('').questions).map(name=>[name,{type:'noul',noul:name==='all_ages'?.99:.01}]));
  if(model===MODERATION_MODELS.jev)answers.violence.noul=.9;
  return {answers};
}}};
const req=(body,headers={},method='POST')=>new Request('https://lab.example/api/compare',{method,headers:{'Authorization':'Bearer test-key','Content-Type':'application/json',...headers},...(method==='POST'?{body:JSON.stringify(body)}:{})});
assert.equal((await worker.fetch(req({prompt:'A friendly flower'},{Authorization:'Bearer wrong'}),env)).status,401);
assert.equal(calls,0);
assert.equal((await worker.fetch(req({prompt:'A friendly flower'},{Origin:'https://evil.example'}),env)).status,403);
assert.equal((await worker.fetch(req({prompt:''}),env)).status,400);
assert.equal((await worker.fetch(req({prompt:'x'.repeat(4001)}),env)).status,400);
assert.equal((await worker.fetch(req({prompt:'A friendly flower'}),{...env,LIMITER:{limit:async()=>({success:false})}})).status,429);
assert.equal(calls,0);
const response=await worker.fetch(req({prompt:'A friendly flower'}),env);
assert.equal(response.status,200);assert.equal(response.headers.get('Cache-Control'),'no-store');
const data=await response.json();assert.equal(calls,3);
assert.deepEqual(data.results.map(x=>x.outcome),['rejected','unavailable','approved']);
assert.deepEqual(data.results[0].reasonCodes,['violence']);assert.equal(data.results[1].allowed,null);
assert.ok(!JSON.stringify(data).includes('private upstream'));
assert.equal((await worker.fetch(req({}, {}, 'GET'),env)).status,405);
assert.equal((await worker.fetch(req({prompt:'A friendly flower'}),{...env,LAB_ACCESS_KEY:undefined})).status,503);
console.log('PASS: access control, origin, input bounds, rate limit, parallel models, partial failures, safe errors and policy decisions');
const login = await worker.fetch(new Request('https://lab.example/api/session',{method:'POST',headers:{Authorization:'Bearer test-key',Origin:'https://lab.example'}}),env);
assert.equal(login.status,200);
const cookie=login.headers.get('Set-Cookie');
assert.match(cookie,/HttpOnly; Secure; SameSite=Strict; Max-Age=2592000/);
assert.ok(!cookie.includes('test-key'));
const sessionRequest=(value=cookie.split(';')[0])=>new Request('https://lab.example/api/session',{headers:{Cookie:value}});
assert.equal((await (await worker.fetch(sessionRequest(),env)).json()).authenticated,true);
assert.equal((await (await worker.fetch(sessionRequest(),{...env,LAB_ACCESS_KEY:'rotated'})).json()).authenticated,false);
assert.equal((await (await worker.fetch(sessionRequest('__Host-lab_session=1.'+'a'.repeat(64)),env)).json()).authenticated,false);
assert.equal((await (await worker.fetch(sessionRequest(cookie.split(';')[0]+'x'),env)).json()).authenticated,false);
assert.equal((await worker.fetch(req({prompt:'A friendly flower'},{Authorization:'',Cookie:cookie.split(';')[0]}),env)).status,403);
assert.equal((await worker.fetch(req({prompt:'A friendly flower'},{Authorization:'',Cookie:cookie.split(';')[0],Origin:'https://lab.example'}),env)).status,200);
const logout=await worker.fetch(new Request('https://lab.example/api/session',{method:'DELETE',headers:{Origin:'https://lab.example'}}),env);
assert.match(logout.headers.get('Set-Cookie'),/Max-Age=0/);
console.log('PASS: signed remembered session, secure cookie, key rotation, expiry, tampering, cookie CSRF protection and logout');
